lexer grammar dola_lexer;

MODULE: 'module';
USE: 'use';
PUB: 'pub';
FN: 'fn';
LET: 'let';
VAR: 'var';
RETURN: 'return';
IF: 'if';
ELSE: 'else';
WHILE: 'while';
FOR: 'for';
IN: 'in';
BREAK: 'break';
CONTINUE: 'continue';
LOOP: 'loop';
RECORD: 'record';
ENUM: 'enum';
MATCH: 'match';
WITH: 'with';
TRUE: 'true';
FALSE: 'false';
UNIT: 'Unit';
BOOL: 'Bool';
INT: 'Int';
FLOAT: 'Float';
STRING: 'String';
OPTION: 'Option';
RESULT: 'Result';
LIST: 'List';
MAP: 'Map';
SENDER: 'Sender';
RECEIVER: 'Receiver';
TASK: 'Task';
LISTENER: 'Listener';
CONNECTION: 'Connection';
SPAWN: 'spawn';
CHANNEL: 'channel';

ARROW: '->';
FAT_ARROW: '=>';
DOTDOT: '..';
OR: '||';
AND: '&&';
EQ: '==';
NE: '!=';
LE: '<=';
GE: '>=';
LT: '<';
GT: '>';
PLUS: '+';
MINUS: '-';
STAR: '*';
SLASH: '/';
PERCENT: '%';
BANG: '!';
QUESTION: '?';
ASSIGN: '=';
DOT: '.';
COMMA: ',';
COLON: ':';
SEMI: ';';
LPAREN: '(';
RPAREN: ')';
LBRACE: '{';
RBRACE: '}';
LBRACKET: '[';
RBRACKET: ']';

FLOAT_LITERAL: [0-9]+ '.' [0-9]+;
INT_LITERAL: [0-9]+;
STRING_LITERAL: '"' (ESCAPE | ~["\\\r\n])* '"';
fragment ESCAPE: '\\' [\\"nrt];
IDENT: [A-Za-z_] [A-Za-z0-9_]*;
LINE_COMMENT: '//' ~[\r\n]* -> skip;
BLOCK_COMMENT: '/*' .*? '*/' -> skip;
WS: [ \t\r\n]+ -> skip;
