load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "runtime",
    srcs = glob([
        "runtime/Cpp/runtime/src/**/*.cpp",
    ]),
    hdrs = glob([
        "runtime/Cpp/runtime/src/**/*.h",
    ]),
    includes = ["runtime/Cpp/runtime/src"],
    defines = ["ANTLR4CPP_STATIC"],
    copts = select({
        "@platforms//os:windows": ["/wd4251"],
        "//conditions:default": ["-Wno-deprecated-declarations", "-Wno-unused-parameter"],
    }),
)
